#!/bin/bash

function infobanner(){
  echo -e " [ INFO ] $1"
}

function okbanner(){
  echo -e "\r [  \033[0;32mOK\033[0;39m  ] $1"
}

function nobanner(){
  echo -e "\r [  \033[0;31mNO\033[0;39m  ] $1"
}

function failbanner(){
  echo -e "\r [ \033[0;31mFAIL\033[0;39m ] $1"
}

function skipbanner(){
  echo -e " [ SKIP ] $1"
}

if [ -v $(which rpi-tools) ]; then
  nobanner "rpi-tools command is not available"
else
  okbanner "rpi-tools command is available"
fi

if [ -v $(which rpi-apps) ]; then
  nobanner "rpi-apps command is not available"
else
  okbanner "rpi-apps command is available"
fi

skipbanner "No script"
