#!/bin/bash

sudo chmod +x ./install/status
./install/status

sudo apt install -y software-properties-common
sudo add-apt-repository ppa:webupd8team/y-ppa-manager
sudo apt update
sudo apt install -y yad
dir=$(pwd)

sudo chmod +x ./install/make
sudo chmod +x ./check/allcheck
./install/make
./check/allcheck
