#!/bin/bash

wget -O dlber.txt https://raw.githubusercontent.com/TamaTamaGoGo/RPi-Tools/latest/check/latestver.txt
wget -O latestver.txt https://raw.githubusercontent.com/TamaTamaGoGo/RPi-Tools/latest/check/latestver.txt


sudo chmod +x ./install/status
./install/status

if [ $(cat latestver.txt) != $(cat ./dlver.txt) ]; then
  ./update
  exit
fi

sudo apt install -y software-properties-common
sudo add-apt-repository ppa:webupd8team/y-ppa-manager
sudo apt update
sudo apt install -y yad
dir=$(pwd)

sudo chmod +x ./install/make
sudo chmod +x ./check/allcheck
./install/make
./check/allcheck
