#!/bin/bash

function infobanner(){
  echo " [  INFO   ] $1"

function commandcheck(){
  infobanner "Checking that '$1' command is not exist"
  if [ -v $(which $1) ]; then
    commandexist=false
    setcommand=$1
  else
    commandexist=true
    infobanner "$1 is already exist!"
    infobanner "You need to set command to other!"
    echo -n "Type other command instead"
    read checkcommand
    commandcheck "$checkcommad"
  fi
}

# This is process to add command rpi-tools
echo ${PATH}
echo "We are about to doing to /usr/bin"

# Process start
cd /usr/bin
mkdir -p "rpi-tools"
