#!/bin/bash

function infobanner(){
  echo " [  INFO   ] $1"
}

function spin()
{
  spinner="\|//-\|//-"
  while :
  do
    for i in $(seq 0 7)
    do
      echo -n " [ ${spinner:$i:1} ] $view"
      echo -en "\010"
      sleep 1
    done
  done
}

function runbanner(){
  view="$1"
  spin &
  SPIN_PID=$!
  $2 &>/dev/null
  view="$3"
  kill $SPIN_PID
}

function commandcheck(){
  infobanner "Checking that '$1' command is not exist"
  if [ -v $(which $1) ]; then
    commandexist=false
    setcommand=$1
  else
    commandexist=true
    infobanner "$1 is already exist!"
    infobanner "You need to set command to other!"
    echo -n "Type other command instead: "
    read -r checkcommand
    commandcheck "$checkcommad"
  fi
}

# Update
sudo true
# runbanner "Updating..." "sudo apt update -y" "Updated    "
# runbanner "Full-Updating.." "sudo apt full-upgrade -y" "Full-updated!    "

# This is process to add command rpi-tools
echo ${PATH}
echo "We are about to doing to /usr/bin"

commandcheck rpi-tools

# Process start
sudo cp -v ./install/script/rpi-tools /usr/bin/${setcommand}
sudo chmod +x /usr/bin/${setcommand}

commandcheck rpi-apps

# Process start
sudo cp -v ./install/script/rpi-apps /usr/bin/${setcommand}
sudo chmod +x /usr/bin/${setcommand}
