#!/bin/bash

echo "Checking that 'rpi-tools' command is not exist"
if [ -v $(which rpi-tools) ]; then
fi

# This is process to add command rpi-tools
echo ${PATH}
echo "We are about to doing to /usr/bin"

# Process start
cd /usr/bin
mkdir -p "rpi-tools"
