#!/bin/bash
# Thanks for https://www.greptips.com/posts/1265/
# Thanks for https://r-h.hatenablog.com/entry/20110119/1295452747

while IFS=, read softname discribe webpage thirtytwobit sixtyfourbit downloadsource
do
  echo -e "\033[1;36m$softname\033[0;39m - $discribe \033[4;37m$webpage\033[0;39m 32bit->\033[1;37m$thirtytwobit\033[0;39m sixtyfourbit->\033[1;37m$sixtyfourbit\033[0;39m \033[4;37m$downloadsource\033[0;39m"
done < $1
