#!/bin/bash

rm -rf source
mkdir source
cd source
wget https://raw.githubusercontent.com/TamaTamaGoGo/RPi-Tools/main/apps/sourcelist-en.csv
wget https://raw.githubusercontent.com/TamaTamaGoGo/RPi-Tools/main/apps/sourcelist-jp.csv
