#!/bin/bash

cd source
yes | rm -rf *
wget https://raw.githubusercontent.com/TamaTamaGoGo/RPi-Tools/main/apps/sourcelist-en.csv
wget https://raw.githubusercontent.com/TamaTamaGoGo/RPi-Tools/main/apps/sourcelist-jp.csv
