#!/bin/bash

# Detect that pwd is in the motd file directory
whereiam=$(./usr/share/RPi-Tools/whereiam)
if [ $whereiam == $(pwd) ]
then
  workdir=''
else
  workdir='${whereiam}/pastime/motd'
fi

function getday(){
  # Get year/month/day
  year=$(date '%Y')
  month=$(date '+%m')
  day=$(data '%d')
}

function getmotd(){
  # Update source
  rm -rf ${dir}motdsource
  wget row~~~
  
}

getday
